import { IScannerRule } from '../types/scanner';
import { Severity, FindingCategory } from '../types/finding';

export const credentialRules: IScannerRule[] = [
  {
    id: 'CRED-001',
    title: 'AWS Access Key Detected',
    description: 'An AWS Access Key ID was found in the code. Move this to environment variables or a secrets manager.',
    severity: Severity.Critical,
    category: FindingCategory.Credential,
    pattern: /AKIA[0-9A-Z]{16}/g,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-002',
    title: 'AWS Secret Key Detected',
    description: 'A potential AWS Secret Access Key was found. Never commit secrets to source control.',
    severity: Severity.Critical,
    category: FindingCategory.Credential,
    pattern: /(?:aws_secret_access_key|aws_secret|secret_key)\s*[:=]\s*['"]?[A-Za-z0-9/+=]{40}['"]?/gi,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-003',
    title: 'Generic API Key Detected',
    description: 'A hardcoded API key was found. Use environment variables or a secrets manager instead.',
    severity: Severity.High,
    category: FindingCategory.Credential,
    pattern: /(?:api[_-]?key|apikey)\s*[:=]\s*['"][A-Za-z0-9]{20,}['"]/gi,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-004',
    title: 'Private Key Detected',
    description: 'A private key was found in the source code. Private keys should never be stored in code.',
    severity: Severity.Critical,
    category: FindingCategory.Credential,
    pattern: /-----BEGIN\s+(?:RSA|DSA|EC|OPENSSH|PGP)?\s*PRIVATE KEY-----/g,
    cweId: 'CWE-321',
  },
  {
    id: 'CRED-005',
    title: 'Hardcoded Password Detected',
    description: 'A hardcoded password was found. Use environment variables or a secrets manager.',
    severity: Severity.High,
    category: FindingCategory.Credential,
    pattern: /(?:password|passwd|pwd)\s*[:=]\s*['"][^'"]{4,}['"]/gi,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-006',
    title: 'GitHub Token Detected',
    description: 'A GitHub personal access token was found. Rotate this token immediately and use environment variables.',
    severity: Severity.Critical,
    category: FindingCategory.Credential,
    pattern: /ghp_[A-Za-z0-9_]{36}/g,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-007',
    title: 'GitHub OAuth Token Detected',
    description: 'A GitHub OAuth access token was found in the code.',
    severity: Severity.Critical,
    category: FindingCategory.Credential,
    pattern: /gho_[A-Za-z0-9_]{36}/g,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-008',
    title: 'Slack Token Detected',
    description: 'A Slack token was found in the code. Rotate and store securely.',
    severity: Severity.Critical,
    category: FindingCategory.Credential,
    pattern: /xox[baprs]-[0-9]{10,13}-[0-9]{10,13}[a-zA-Z0-9-]*/g,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-009',
    title: 'Generic Secret Assignment',
    description: 'A potential secret was found hardcoded in the source. Move to environment variables.',
    severity: Severity.High,
    category: FindingCategory.Credential,
    pattern: /(?:secret|token|auth)\s*[:=]\s*['"][A-Za-z0-9+/=]{20,}['"]/gi,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-010',
    title: 'Connection String with Credentials',
    description: 'A database connection string with embedded credentials was detected.',
    severity: Severity.High,
    category: FindingCategory.Credential,
    pattern: /(?:mongodb|postgres|mysql|redis|amqp):\/\/[^:\s]+:[^@\s]+@[^/\s]+/gi,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-011',
    title: 'Google API Key Detected',
    description: 'A Google API key was found. Restrict key usage and use environment variables.',
    severity: Severity.High,
    category: FindingCategory.Credential,
    pattern: /AIza[0-9A-Za-z_-]{35}/g,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-012',
    title: 'Stripe Secret Key Detected',
    description: 'A Stripe secret key was found. This grants full API access. Rotate immediately.',
    severity: Severity.Critical,
    category: FindingCategory.Credential,
    pattern: /sk_live_[0-9a-zA-Z]{24,}/g,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-013',
    title: 'JWT Token Detected',
    description: 'A hardcoded JWT token was found. Tokens should be generated dynamically.',
    severity: Severity.Medium,
    category: FindingCategory.Credential,
    pattern: /eyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}/g,
    cweId: 'CWE-798',
  },
];
