import { IScannerRule } from '../types/scanner';
import { Severity, FindingCategory } from '../types/finding';

export const misconfigRules: IScannerRule[] = [
  {
    id: 'MISC-001',
    title: 'Insecure HTTP URL',
    description: 'Non-localhost HTTP URL detected. Use HTTPS for secure communication.',
    severity: Severity.Medium,
    category: FindingCategory.Misconfiguration,
    pattern: /http:\/\/(?!localhost|127\.0\.0\.1|0\.0\.0\.0|::1)[a-zA-Z0-9][a-zA-Z0-9.-]+/g,
    cweId: 'CWE-319',
  },
  {
    id: 'MISC-002',
    title: 'Wildcard CORS Configuration',
    description: 'CORS is configured to allow all origins. Restrict to specific trusted domains.',
    severity: Severity.High,
    category: FindingCategory.Misconfiguration,
    pattern: /(?:cors\(\s*\{\s*origin:\s*['"]?\*['"]?|Access-Control-Allow-Origin:\s*\*)/g,
    cweId: 'CWE-942',
  },
  {
    id: 'MISC-003',
    title: 'TLS Certificate Verification Disabled',
    description: 'TLS certificate verification is disabled, allowing man-in-the-middle attacks.',
    severity: Severity.Critical,
    category: FindingCategory.Misconfiguration,
    pattern: /(?:NODE_TLS_REJECT_UNAUTHORIZED\s*=\s*['"]?0|rejectUnauthorized\s*:\s*false|verify\s*=\s*False)/g,
    cweId: 'CWE-295',
  },
  {
    id: 'MISC-004',
    title: 'Debug Mode Enabled',
    description: 'Debug mode appears to be enabled. Ensure this is disabled in production.',
    severity: Severity.Medium,
    category: FindingCategory.Misconfiguration,
    pattern: /(?:DEBUG\s*[:=]\s*(?:true|True|1|['"]true['"])|app\.debug\s*=\s*True)/g,
    cweId: 'CWE-215',
  },
  {
    id: 'MISC-005',
    title: 'Insecure Random Number Generator',
    description: 'Math.random() is not cryptographically secure. Use crypto.randomBytes() for security purposes.',
    severity: Severity.Medium,
    category: FindingCategory.Misconfiguration,
    pattern: /Math\.random\s*\(\)/g,
    languages: ['javascript', 'typescript'],
    cweId: 'CWE-338',
  },
  {
    id: 'MISC-006',
    title: 'Empty Catch Block',
    description: 'Empty catch block silently swallows errors. Log or handle errors appropriately.',
    severity: Severity.Low,
    category: FindingCategory.Misconfiguration,
    pattern: /catch\s*\([^)]*\)\s*\{\s*\}/g,
    cweId: 'CWE-390',
  },
  {
    id: 'MISC-007',
    title: 'Hardcoded IP Address',
    description: 'Hardcoded IP address found. Use configuration files or environment variables.',
    severity: Severity.Low,
    category: FindingCategory.Misconfiguration,
    pattern: /['"](?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)['"]/g,
    cweId: 'CWE-547',
  },
  {
    id: 'MISC-008',
    title: 'Helmet.js Not Used',
    description: 'Express app without Helmet security headers middleware detected.',
    severity: Severity.Medium,
    category: FindingCategory.Misconfiguration,
    pattern: /app\s*=\s*express\s*\(\)/g,
    languages: ['javascript', 'typescript'],
    cweId: 'CWE-693',
  },
  {
    id: 'MISC-009',
    title: 'Console.log in Production Code',
    description: 'console.log statements may leak sensitive information in production.',
    severity: Severity.Info,
    category: FindingCategory.Misconfiguration,
    pattern: /console\.log\s*\(/g,
    languages: ['javascript', 'typescript'],
    cweId: 'CWE-532',
  },
  {
    id: 'MISC-010',
    title: 'Binding to All Interfaces (0.0.0.0)',
    description: 'Server is binding to all network interfaces. Consider binding to a specific interface.',
    severity: Severity.Medium,
    category: FindingCategory.Misconfiguration,
    pattern: /(?:listen|bind)\s*\(\s*(?:['"]0\.0\.0\.0['"]|0\.0\.0\.0)/g,
    cweId: 'CWE-668',
  },
];
