import { IScannerRule } from '../types/scanner';
import { Severity, FindingCategory } from '../types/finding';

export const owaspRules: IScannerRule[] = [
  // A03:2021 - Injection
  {
    id: 'OWASP-001',
    title: 'Potential SQL Injection',
    description: 'String concatenation in SQL query detected. Use parameterized queries instead.',
    severity: Severity.Critical,
    category: FindingCategory.OWASP,
    pattern: /(?:query|execute|exec)\s*\(\s*['"`](?:SELECT|INSERT|UPDATE|DELETE|DROP|CREATE|ALTER)\s[^'"`]*['"`]\s*\+/gi,
    languages: ['javascript', 'typescript', 'python', 'java', 'php'],
    cweId: 'CWE-89',
    owaspId: 'A03:2021',
  },
  {
    id: 'OWASP-002',
    title: 'SQL Injection via Template Literal',
    description: 'SQL query uses template literal with interpolated values. Use parameterized queries.',
    severity: Severity.Critical,
    category: FindingCategory.OWASP,
    pattern: /(?:query|execute|exec)\s*\(\s*`(?:SELECT|INSERT|UPDATE|DELETE|DROP)\s[^`]*\$\{/gi,
    languages: ['javascript', 'typescript'],
    cweId: 'CWE-89',
    owaspId: 'A03:2021',
  },
  {
    id: 'OWASP-003',
    title: 'Use of eval() - Code Injection Risk',
    description: 'eval() executes arbitrary code and is a major security risk. Avoid eval entirely.',
    severity: Severity.Critical,
    category: FindingCategory.OWASP,
    pattern: /\beval\s*\(/g,
    languages: ['javascript', 'typescript', 'python'],
    cweId: 'CWE-95',
    owaspId: 'A03:2021',
  },
  {
    id: 'OWASP-004',
    title: 'Use of Function() Constructor',
    description: 'The Function constructor creates functions from strings, similar to eval(). Avoid it.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /new\s+Function\s*\(/g,
    languages: ['javascript', 'typescript'],
    cweId: 'CWE-95',
    owaspId: 'A03:2021',
  },
  // A03:2021 - XSS
  {
    id: 'OWASP-005',
    title: 'Potential XSS via innerHTML',
    description: 'Setting innerHTML with dynamic content can lead to XSS. Use textContent or sanitize input.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /\.innerHTML\s*=/g,
    languages: ['javascript', 'typescript'],
    cweId: 'CWE-79',
    owaspId: 'A03:2021',
  },
  {
    id: 'OWASP-006',
    title: 'Potential XSS via document.write',
    description: 'document.write() can introduce XSS vulnerabilities. Use DOM manipulation methods instead.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /document\.write\s*\(/g,
    languages: ['javascript', 'typescript'],
    cweId: 'CWE-79',
    owaspId: 'A03:2021',
  },
  {
    id: 'OWASP-007',
    title: 'React dangerouslySetInnerHTML',
    description: 'dangerouslySetInnerHTML can lead to XSS if not properly sanitized.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /dangerouslySetInnerHTML/g,
    languages: ['javascript', 'typescript', 'javascriptreact', 'typescriptreact'],
    cweId: 'CWE-79',
    owaspId: 'A03:2021',
  },
  // A08:2021 - Insecure Deserialization
  {
    id: 'OWASP-008',
    title: 'Insecure Deserialization (pickle)',
    description: 'pickle.loads() can execute arbitrary code. Use json or safe alternatives.',
    severity: Severity.Critical,
    category: FindingCategory.OWASP,
    pattern: /pickle\.loads?\s*\(/g,
    languages: ['python'],
    cweId: 'CWE-502',
    owaspId: 'A08:2021',
  },
  {
    id: 'OWASP-009',
    title: 'Insecure YAML Loading',
    description: 'yaml.load() without SafeLoader can execute arbitrary code. Use yaml.safe_load() instead.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /yaml\.load\s*\([^)]*(?!Loader\s*=\s*yaml\.SafeLoader)[^)]*\)/g,
    languages: ['python'],
    cweId: 'CWE-502',
    owaspId: 'A08:2021',
  },
  // A02:2021 - Cryptographic Failures
  {
    id: 'OWASP-010',
    title: 'Weak Cryptographic Algorithm (MD5)',
    description: 'MD5 is cryptographically broken. Use SHA-256 or stronger algorithms.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /(?:createHash|hashlib\.md5|MD5|MessageDigest\.getInstance)\s*\(\s*['"]?md5['"]?\s*\)/gi,
    cweId: 'CWE-327',
    owaspId: 'A02:2021',
  },
  {
    id: 'OWASP-011',
    title: 'Weak Cryptographic Algorithm (SHA1)',
    description: 'SHA-1 is deprecated for security use. Use SHA-256 or stronger.',
    severity: Severity.Medium,
    category: FindingCategory.OWASP,
    pattern: /(?:createHash|hashlib\.sha1|MessageDigest\.getInstance)\s*\(\s*['"]?sha1['"]?\s*\)/gi,
    cweId: 'CWE-327',
    owaspId: 'A02:2021',
  },
  // A07:2021 - Command Injection
  {
    id: 'OWASP-012',
    title: 'Potential Command Injection',
    description: 'User input in shell commands can lead to command injection. Use parameterized commands.',
    severity: Severity.Critical,
    category: FindingCategory.OWASP,
    pattern: /(?:exec|spawn|execSync|spawnSync|system|popen)\s*\(\s*(?:['"`][^'"`]*['"`]\s*\+|`[^`]*\$\{)/g,
    cweId: 'CWE-78',
    owaspId: 'A03:2021',
  },
  {
    id: 'OWASP-013',
    title: 'Python os.system() Usage',
    description: 'os.system() is vulnerable to command injection. Use subprocess with shell=False.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /os\.system\s*\(/g,
    languages: ['python'],
    cweId: 'CWE-78',
    owaspId: 'A03:2021',
  },
  // A05:2021 - Security Misconfiguration
  {
    id: 'OWASP-014',
    title: 'Disabled CSRF Protection',
    description: 'CSRF protection appears to be disabled. Ensure CSRF tokens are validated.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /(?:csrf|xsrf)\s*[:=]\s*(?:false|disabled|off)/gi,
    cweId: 'CWE-352',
    owaspId: 'A05:2021',
  },
  // A01:2021 - Broken Access Control
  {
    id: 'OWASP-015',
    title: 'Potential Path Traversal',
    description: 'File path constructed from user input may allow path traversal attacks.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /(?:readFile|readFileSync|open|createReadStream)\s*\(\s*(?:req\.|request\.|params\.|query\.)/g,
    languages: ['javascript', 'typescript'],
    cweId: 'CWE-22',
    owaspId: 'A01:2021',
  },
];
